import { StyleSheet } from "react-native";

const styled = StyleSheet.create({
  calendar: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    position: "relative",
    width: "100%",
  },
  back: {
    position: "absolute",
    // z-index: -1,
    top: 0,
    left: 0,
    width: "100%",
    height: 370,
  },
  backImg: {
    width: "100%",
    flex: 1,
    objectFit: "cover",
  },
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-around",
    position: "relative",
    width: "100%",
    background: "#F3EDDF",
  },
  title: {
    fontWeight: 500,
    textTransform: "uppercase",
    width: "70%",
    textAlign: "center",
    color: "#0C0300",
    marginBottom: 15,
  },
  descr: {
    textAlign: "center",
    fontWeight: 300,
    width: "80%",
    marginBottom: 35,
  },
  icon: {
    width: 55,
    height: 55,
    objectFit: "contain",
  },
  divider: {
    width: "94%",
    height: 1,
    backgroundColor: "#0C0300",
    opacity: 0.2,
    marginVertical: 30,
    alignSelf: "center",
  },
  item: {
    position: "relative",
    width: "90%",
    borderRadius: 20,
    zIndex: 2,
    backgroundColor: "transparent",
    marginBottom: 15,
  },
  text: {
    textTransform: "lowercase",
    textAlign: "center",
    color: "#ffffff",
    fontWeight: 500,
  },
  date: {
    textAlign: "center",
    color: "#F55926",
    marginHorizontal: 16,
    marginTop: 11,
    marginBottom: 18,
  },
  shadow: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 5,
    left: 0,
    borderRadius: 20,
    zIndex: 2,
    borderColor: "#F55926",
    borderStyle: "solid",
    borderWidth: 1,
  },
  price: {
    color: "#ffffff",
    fontWeight: 700,
    textAlign: "center",
  },
  plan: {
    alignSelf: "center",
    width: "65%",
    paddingVertical: 20,
    position: 'relative',
  },

  backDown: {
    position: 'absolute',
    zIndex: -1,
    bottom: 0,
    left: 0,
    width: "100%",
    height: 370,
    objectFit: "cover",
  },
  input: {
    backgroundColor: "white",
    width: "90%",
    borderRadius: 20,
    borderColor: "rgba(12, 3, 0, 0.50)",
    borderWidth: 1,
    borderStyle: "solid",
    fontSize: 16,
    padding: 15,
    marginBottom: 20,
  },
  iconContainer: {
    position: "absolute",
    top: 2,
    right: 0,
    width: 50,
    height: 50,
  },
  iconCalendar: {
    width: 50,
    height: 50,
    objectFit: "contain",
  },
  picker: {
    position: "absolute",
    width: "100%",
    top: 0,
    right: 0,
    zIndex: 5,
    backgroundColor: "#F3EDDF",
  },
  block: {
    // width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",

  },
  img: {
    paddingVertical: 80,
    width: "100%",
  },
});

export default styled;
